from __future__ import annotations

from pathlib import Path

import pandas as pd

from spaDTA.model.workflow import run_all_samples


package_root = Path(__file__).resolve().parents[1]
processed_root = Path("/bigdat2/user/hesy/spatialmeta/SpatialMETA/processed")
gt_root = Path("/bigdat2/user/hesy/spatialmeta/SpatialMETA/06_spatialmeta_groundtruth/06_spatialmeta_groundtruth")
output_root = package_root / "runs" / "model_runs" / "current_localcontext_contrastive_w002_fixed_targetcount_20260427_localized"
config_name = "ablate_no_hete_homo_splitrecon_sharedhalf_balance"
sample_names = [
    "248_T",
    "R114_T",
    "S15_T",
    "X49_T",
    "Y27_T",
    "Y7_T",
    "m1_FMP",
    "m3_FMP",
    "m4_FMP",
]
device = "cuda:0"
train_kwargs_by_sample = {
    "248_T": {
        "device": device, "max_epoch": 128, "n_per_batch": 128, "proj_dim": 256, "token_dim": 128, "n_latent": 10,
        "num_prototypes": 8, "max_cells": 0, "random_seed": 42, "cluster_random_seed": 0, "dropout_rate": 0.03,
        "cluster_n_neighbors": 15, "cluster_resolution": 0.96, "reconstruction_st_weight": 0.75, "reconstruction_sm_weight": 0.25,
        "dec_weight": 1.0, "hete_weight": 0.0, "homo_weight": 0.01, "hete_warmup_epochs": 0, "homo_warmup_epochs": 0,
        "kl_weight": 0.0, "n_epochs_kl_warmup": 0, "lr": 5e-4, "weight_decay": 1e-6, "reconstruction_reduction": "mean",
        "reconstruction_method_st": "zinb", "reconstruction_method_sm": "g", "balance_start_epoch": 16, "balance_ema": 0.8,
        "balance_weight_floor": 0.05, "spatial_coord_hidden_dim": 128, "spatial_context_hidden_dim": 128, "spatial_context_k": 12,
        "spatial_encoder_mode": "local_context", "spatial_fourier_scales": (1.0, 2.0, 4.0), "spatial_token_scale": 0.5,
        "spatial_token_dropout": 0.15, "spatial_consistency_weight": 0.0, "spatial_consistency_warmup_epochs": 16,
        "spatial_contrastive_weight": 0.02, "spatial_contrastive_warmup_epochs": 16, "spatial_contrastive_pos_k": 4,
        "spatial_contrastive_neg_k": 16, "spatial_contrastive_temperature": 0.2, "spatial_contrastive_neg_strategy": "mid",
        "standardize_inputs": False, "standardized_reconstruction": False, "deterministic": False, "deterministic_warn_only": False,
        "spatial_consistency_use_all_latent": False, "spatial_contrastive_use_all_latent": False,
    },
    "R114_T": {
        "device": device, "max_epoch": 128, "n_per_batch": 128, "proj_dim": 256, "token_dim": 128, "n_latent": 10,
        "num_prototypes": 8, "max_cells": 0, "random_seed": 42, "cluster_random_seed": 0, "dropout_rate": 0.03,
        "cluster_n_neighbors": 15, "cluster_resolution": 0.36, "reconstruction_st_weight": 0.75, "reconstruction_sm_weight": 0.25,
        "dec_weight": 1.0, "hete_weight": 0.0, "homo_weight": 0.01, "hete_warmup_epochs": 0, "homo_warmup_epochs": 0,
        "kl_weight": 0.0, "n_epochs_kl_warmup": 0, "lr": 5e-4, "weight_decay": 1e-6, "reconstruction_reduction": "mean",
        "reconstruction_method_st": "zinb", "reconstruction_method_sm": "g", "balance_start_epoch": 16, "balance_ema": 0.8,
        "balance_weight_floor": 0.05, "spatial_coord_hidden_dim": 128, "spatial_context_hidden_dim": 128, "spatial_context_k": 12,
        "spatial_encoder_mode": "local_context", "spatial_fourier_scales": (1.0, 2.0, 4.0), "spatial_token_scale": 0.5,
        "spatial_token_dropout": 0.15, "spatial_consistency_weight": 0.0, "spatial_consistency_warmup_epochs": 16,
        "spatial_contrastive_weight": 0.02, "spatial_contrastive_warmup_epochs": 16, "spatial_contrastive_pos_k": 4,
        "spatial_contrastive_neg_k": 16, "spatial_contrastive_temperature": 0.2, "spatial_contrastive_neg_strategy": "mid",
        "standardize_inputs": False, "standardized_reconstruction": False, "deterministic": False, "deterministic_warn_only": False,
        "spatial_consistency_use_all_latent": False, "spatial_contrastive_use_all_latent": False,
    },
    "S15_T": {
        "device": device, "max_epoch": 128, "n_per_batch": 128, "proj_dim": 256, "token_dim": 128, "n_latent": 10,
        "num_prototypes": 8, "max_cells": 0, "random_seed": 42, "cluster_random_seed": 0, "dropout_rate": 0.03,
        "cluster_n_neighbors": 15, "cluster_resolution": 0.56, "reconstruction_st_weight": 0.75, "reconstruction_sm_weight": 0.25,
        "dec_weight": 1.0, "hete_weight": 0.0, "homo_weight": 0.01, "hete_warmup_epochs": 0, "homo_warmup_epochs": 0,
        "kl_weight": 0.0, "n_epochs_kl_warmup": 0, "lr": 5e-4, "weight_decay": 1e-6, "reconstruction_reduction": "mean",
        "reconstruction_method_st": "zinb", "reconstruction_method_sm": "g", "balance_start_epoch": 16, "balance_ema": 0.8,
        "balance_weight_floor": 0.05, "spatial_coord_hidden_dim": 128, "spatial_context_hidden_dim": 128, "spatial_context_k": 12,
        "spatial_encoder_mode": "local_context", "spatial_fourier_scales": (1.0, 2.0, 4.0), "spatial_token_scale": 0.5,
        "spatial_token_dropout": 0.15, "spatial_consistency_weight": 0.0, "spatial_consistency_warmup_epochs": 16,
        "spatial_contrastive_weight": 0.02, "spatial_contrastive_warmup_epochs": 16, "spatial_contrastive_pos_k": 4,
        "spatial_contrastive_neg_k": 16, "spatial_contrastive_temperature": 0.2, "spatial_contrastive_neg_strategy": "mid",
        "standardize_inputs": False, "standardized_reconstruction": False, "deterministic": False, "deterministic_warn_only": False,
        "spatial_consistency_use_all_latent": False, "spatial_contrastive_use_all_latent": False,
    },
    "X49_T": {
        "device": device, "max_epoch": 128, "n_per_batch": 128, "proj_dim": 256, "token_dim": 128, "n_latent": 10,
        "num_prototypes": 8, "max_cells": 0, "random_seed": 42, "cluster_random_seed": 0, "dropout_rate": 0.03,
        "cluster_n_neighbors": 15, "cluster_resolution": 0.41, "reconstruction_st_weight": 0.75, "reconstruction_sm_weight": 0.25,
        "dec_weight": 1.0, "hete_weight": 0.0, "homo_weight": 0.01, "hete_warmup_epochs": 0, "homo_warmup_epochs": 0,
        "kl_weight": 0.0, "n_epochs_kl_warmup": 0, "lr": 5e-4, "weight_decay": 1e-6, "reconstruction_reduction": "mean",
        "reconstruction_method_st": "zinb", "reconstruction_method_sm": "g", "balance_start_epoch": 16, "balance_ema": 0.8,
        "balance_weight_floor": 0.05, "spatial_coord_hidden_dim": 128, "spatial_context_hidden_dim": 128, "spatial_context_k": 12,
        "spatial_encoder_mode": "local_context", "spatial_fourier_scales": (1.0, 2.0, 4.0), "spatial_token_scale": 0.5,
        "spatial_token_dropout": 0.15, "spatial_consistency_weight": 0.0, "spatial_consistency_warmup_epochs": 16,
        "spatial_contrastive_weight": 0.02, "spatial_contrastive_warmup_epochs": 16, "spatial_contrastive_pos_k": 4,
        "spatial_contrastive_neg_k": 16, "spatial_contrastive_temperature": 0.2, "spatial_contrastive_neg_strategy": "mid",
        "standardize_inputs": False, "standardized_reconstruction": False, "deterministic": False, "deterministic_warn_only": False,
        "spatial_consistency_use_all_latent": False, "spatial_contrastive_use_all_latent": False,
    },
    "Y27_T": {
        "device": device, "max_epoch": 128, "n_per_batch": 128, "proj_dim": 256, "token_dim": 128, "n_latent": 10,
        "num_prototypes": 8, "max_cells": 0, "random_seed": 42, "cluster_random_seed": 0, "dropout_rate": 0.03,
        "cluster_n_neighbors": 15, "cluster_resolution": 0.37, "reconstruction_st_weight": 0.75, "reconstruction_sm_weight": 0.25,
        "dec_weight": 1.0, "hete_weight": 0.0, "homo_weight": 0.01, "hete_warmup_epochs": 0, "homo_warmup_epochs": 0,
        "kl_weight": 0.0, "n_epochs_kl_warmup": 0, "lr": 5e-4, "weight_decay": 1e-6, "reconstruction_reduction": "mean",
        "reconstruction_method_st": "zinb", "reconstruction_method_sm": "g", "balance_start_epoch": 16, "balance_ema": 0.8,
        "balance_weight_floor": 0.05, "spatial_coord_hidden_dim": 128, "spatial_context_hidden_dim": 128, "spatial_context_k": 12,
        "spatial_encoder_mode": "local_context", "spatial_fourier_scales": (1.0, 2.0, 4.0), "spatial_token_scale": 0.5,
        "spatial_token_dropout": 0.15, "spatial_consistency_weight": 0.0, "spatial_consistency_warmup_epochs": 16,
        "spatial_contrastive_weight": 0.02, "spatial_contrastive_warmup_epochs": 16, "spatial_contrastive_pos_k": 4,
        "spatial_contrastive_neg_k": 16, "spatial_contrastive_temperature": 0.2, "spatial_contrastive_neg_strategy": "mid",
        "standardize_inputs": False, "standardized_reconstruction": False, "deterministic": False, "deterministic_warn_only": False,
        "spatial_consistency_use_all_latent": False, "spatial_contrastive_use_all_latent": False,
    },
    "Y7_T": {
        "device": device, "max_epoch": 128, "n_per_batch": 128, "proj_dim": 256, "token_dim": 128, "n_latent": 10,
        "num_prototypes": 8, "max_cells": 0, "random_seed": 42, "cluster_random_seed": 0, "dropout_rate": 0.03,
        "cluster_n_neighbors": 15, "cluster_resolution": 0.798, "reconstruction_st_weight": 0.75, "reconstruction_sm_weight": 0.25,
        "dec_weight": 1.0, "hete_weight": 0.0, "homo_weight": 0.01, "hete_warmup_epochs": 0, "homo_warmup_epochs": 0,
        "kl_weight": 0.0, "n_epochs_kl_warmup": 0, "lr": 5e-4, "weight_decay": 1e-6, "reconstruction_reduction": "mean",
        "reconstruction_method_st": "zinb", "reconstruction_method_sm": "g", "balance_start_epoch": 16, "balance_ema": 0.8,
        "balance_weight_floor": 0.05, "spatial_coord_hidden_dim": 128, "spatial_context_hidden_dim": 128, "spatial_context_k": 12,
        "spatial_encoder_mode": "local_context", "spatial_fourier_scales": (1.0, 2.0, 4.0), "spatial_token_scale": 0.5,
        "spatial_token_dropout": 0.15, "spatial_consistency_weight": 0.0, "spatial_consistency_warmup_epochs": 16,
        "spatial_contrastive_weight": 0.02, "spatial_contrastive_warmup_epochs": 16, "spatial_contrastive_pos_k": 4,
        "spatial_contrastive_neg_k": 16, "spatial_contrastive_temperature": 0.2, "spatial_contrastive_neg_strategy": "mid",
        "standardize_inputs": False, "standardized_reconstruction": False, "deterministic": False, "deterministic_warn_only": False,
        "spatial_consistency_use_all_latent": False, "spatial_contrastive_use_all_latent": False,
    },
    "m1_FMP": {
        "device": device, "max_epoch": 128, "n_per_batch": 128, "proj_dim": 256, "token_dim": 128, "n_latent": 10,
        "num_prototypes": 8, "max_cells": 0, "random_seed": 42, "cluster_random_seed": 0, "dropout_rate": 0.03,
        "cluster_n_neighbors": 15, "cluster_resolution": 0.56, "reconstruction_st_weight": 0.75, "reconstruction_sm_weight": 0.25,
        "dec_weight": 1.0, "hete_weight": 0.0, "homo_weight": 0.01, "hete_warmup_epochs": 0, "homo_warmup_epochs": 0,
        "kl_weight": 0.0, "n_epochs_kl_warmup": 0, "lr": 5e-4, "weight_decay": 1e-6, "reconstruction_reduction": "mean",
        "reconstruction_method_st": "zinb", "reconstruction_method_sm": "g", "balance_start_epoch": 16, "balance_ema": 0.8,
        "balance_weight_floor": 0.05, "spatial_coord_hidden_dim": 128, "spatial_context_hidden_dim": 128, "spatial_context_k": 12,
        "spatial_encoder_mode": "local_context", "spatial_fourier_scales": (1.0, 2.0, 4.0), "spatial_token_scale": 0.5,
        "spatial_token_dropout": 0.15, "spatial_consistency_weight": 0.0, "spatial_consistency_warmup_epochs": 16,
        "spatial_contrastive_weight": 0.02, "spatial_contrastive_warmup_epochs": 16, "spatial_contrastive_pos_k": 4,
        "spatial_contrastive_neg_k": 16, "spatial_contrastive_temperature": 0.2, "spatial_contrastive_neg_strategy": "mid",
        "standardize_inputs": False, "standardized_reconstruction": False, "deterministic": False, "deterministic_warn_only": False,
        "spatial_consistency_use_all_latent": False, "spatial_contrastive_use_all_latent": False,
    },
    "m3_FMP": {
        "device": device, "max_epoch": 128, "n_per_batch": 128, "proj_dim": 256, "token_dim": 128, "n_latent": 10,
        "num_prototypes": 8, "max_cells": 0, "random_seed": 42, "cluster_random_seed": 0, "dropout_rate": 0.03,
        "cluster_n_neighbors": 15, "cluster_resolution": 0.41, "reconstruction_st_weight": 0.75, "reconstruction_sm_weight": 0.25,
        "dec_weight": 1.0, "hete_weight": 0.0, "homo_weight": 0.01, "hete_warmup_epochs": 0, "homo_warmup_epochs": 0,
        "kl_weight": 0.0, "n_epochs_kl_warmup": 0, "lr": 5e-4, "weight_decay": 1e-6, "reconstruction_reduction": "mean",
        "reconstruction_method_st": "zinb", "reconstruction_method_sm": "g", "balance_start_epoch": 16, "balance_ema": 0.8,
        "balance_weight_floor": 0.05, "spatial_coord_hidden_dim": 128, "spatial_context_hidden_dim": 128, "spatial_context_k": 12,
        "spatial_encoder_mode": "local_context", "spatial_fourier_scales": (1.0, 2.0, 4.0), "spatial_token_scale": 0.5,
        "spatial_token_dropout": 0.15, "spatial_consistency_weight": 0.0, "spatial_consistency_warmup_epochs": 16,
        "spatial_contrastive_weight": 0.02, "spatial_contrastive_warmup_epochs": 16, "spatial_contrastive_pos_k": 4,
        "spatial_contrastive_neg_k": 16, "spatial_contrastive_temperature": 0.2, "spatial_contrastive_neg_strategy": "mid",
        "standardize_inputs": False, "standardized_reconstruction": False, "deterministic": False, "deterministic_warn_only": False,
        "spatial_consistency_use_all_latent": False, "spatial_contrastive_use_all_latent": False,
    },
    "m4_FMP": {
        "device": device, "max_epoch": 128, "n_per_batch": 128, "proj_dim": 256, "token_dim": 128, "n_latent": 10,
        "num_prototypes": 8, "max_cells": 0, "random_seed": 42, "cluster_random_seed": 0, "dropout_rate": 0.03,
        "cluster_n_neighbors": 15, "cluster_resolution": 0.46, "reconstruction_st_weight": 0.75, "reconstruction_sm_weight": 0.25,
        "dec_weight": 1.0, "hete_weight": 0.0, "homo_weight": 0.01, "hete_warmup_epochs": 0, "homo_warmup_epochs": 0,
        "kl_weight": 0.0, "n_epochs_kl_warmup": 0, "lr": 5e-4, "weight_decay": 1e-6, "reconstruction_reduction": "mean",
        "reconstruction_method_st": "zinb", "reconstruction_method_sm": "g", "balance_start_epoch": 16, "balance_ema": 0.8,
        "balance_weight_floor": 0.05, "spatial_coord_hidden_dim": 128, "spatial_context_hidden_dim": 128, "spatial_context_k": 12,
        "spatial_encoder_mode": "local_context", "spatial_fourier_scales": (1.0, 2.0, 4.0), "spatial_token_scale": 0.5,
        "spatial_token_dropout": 0.15, "spatial_consistency_weight": 0.0, "spatial_consistency_warmup_epochs": 16,
        "spatial_contrastive_weight": 0.02, "spatial_contrastive_warmup_epochs": 16, "spatial_contrastive_pos_k": 4,
        "spatial_contrastive_neg_k": 16, "spatial_contrastive_temperature": 0.2, "spatial_contrastive_neg_strategy": "mid",
        "standardize_inputs": False, "standardized_reconstruction": False, "deterministic": False, "deterministic_warn_only": False,
        "spatial_consistency_use_all_latent": False, "spatial_contrastive_use_all_latent": False,
    },
}

summary_df = run_all_samples(
    sample_names=sample_names,
    train_kwargs_by_sample=train_kwargs_by_sample,
    processed_root=processed_root,
    gt_root=gt_root,
    output_root=output_root,
    config_name=config_name,
)
if not summary_df.empty:
    print(summary_df[["sample", "pred_clusters", "ARI", "NMI"]].to_string(index=False))
